### ISSUE TITLE
Expand django version pin to permit >4.1

### ISSUE THREAD

**Issue by scnerd** [mounirmesselmeni/django-highlightjs#13]
I get the following when attempting to install `django-highlightjs==0.2.8` with `django==4.1.5` pinned:

```
...
django-highlightjs 0.2.8 depends on Django==4.1
```

I think the pin should instead be `Django~=4.1`?

**Comment by mounirmesselmeni** [comment]
Thanks for reporting, fixed in version 0.2.11

closed via 521be0d
